# Feature Experiment Report

- Base run: `v000022`
- Threshold: `0.3`
- Class weight: `balanced_subsample`
- Train datasets: `['v000003', 'v000006']`
- Test datasets: `['v000004', 'v000005']`
- Output dir: `/Users/yes/ML_teamproject/outputs/feature_experiments/run_v000022`

이 노트북은 이미 생성된 CSV/PNG를 보기 좋게 묶은 리포트입니다. 셀을 다시 실행해도 공식 run 산출물은 수정하지 않습니다.

In [ ]:
from pathlib import Path
import pandas as pd
from IPython.display import Image, display

OUTPUT_DIR = Path('/Users/yes/ML_teamproject/outputs/feature_experiments/run_v000022')
metrics = pd.read_csv(OUTPUT_DIR / 'metrics_summary.csv')
confusion = pd.read_csv(OUTPUT_DIR / 'confusion_matrices.csv')
importances = pd.read_csv(OUTPUT_DIR / 'feature_importances.csv')
statistics = pd.read_csv(OUTPUT_DIR / 'feature_statistics.csv')
probability = pd.read_csv(OUTPUT_DIR / 'probability_summary.csv')
plots = OUTPUT_DIR / 'plots'

## 1. 전체 feature set 성능 요약

In [1]:
# metrics
metrics

                                  feature_set  feature_count    TN   FP   FN    TP  precision   recall       f1       f2  false_positive_rate  false_negative_rate
                        dropped_shortcut_only             12 60715 5065    0 16445   0.764528 1.000000 0.866552 0.941975             0.076999             0.000000
                       shortcut_suspects_only             22 64661 1119 3428 13017   0.920840 0.791548 0.851313 0.814418             0.017011             0.208452
                   add_back_dropped__src_port             39 65318  462 4183 12262   0.963691 0.745637 0.840756 0.780979             0.007023             0.254363
            ablate_top__additional_AAAA_count             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
               ablate_top__additional_A_count             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
ablate_top__additional_out_of_bailiwick_count             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                   ablate_top__answer_A_count             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
              ablate_top__answer_record_count             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                 ablate_top__dns_count_add_rr             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                ablate_top__dns_count_answers             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                 ablate_top__has_additional_A             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                     ablate_top__record_total             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
         ablate_top__unique_record_name_count             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
              add_back_dropped__frame_cap_len             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                     add_back_dropped__ip_len             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
              add_back_dropped__query_entropy             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
          add_back_dropped__query_label_count             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
             add_back_dropped__query_name_len             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                    add_back_dropped__ttl_max             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                   add_back_dropped__ttl_mean             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                    add_back_dropped__ttl_min             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                 add_back_dropped__udp_length             39 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                                  all_current             38 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                           dns_structure_only             31 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
                          top_importance_only             10 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407

## 2. 기준 all_current와 recall 상위 feature set

In [1]:
# baseline_all_current
baseline_all_current

feature_set  feature_count    TN  FP   FN   TP  precision   recall       f1       f2  false_positive_rate  false_negative_rate
all_current             38 65780   0 9183 7262        1.0 0.441593 0.612646 0.497111                  0.0             0.558407

In [1]:
# top_recall_feature_sets
top_recall_feature_sets

                      feature_set  feature_count    TN   FP   FN    TP  precision   recall       f1       f2  false_positive_rate  false_negative_rate
            dropped_shortcut_only             12 60715 5065    0 16445   0.764528 1.000000 0.866552 0.941975             0.076999             0.000000
           shortcut_suspects_only             22 64661 1119 3428 13017   0.920840 0.791548 0.851313 0.814418             0.017011             0.208452
       add_back_dropped__src_port             39 65318  462 4183 12262   0.963691 0.745637 0.840756 0.780979             0.007023             0.254363
ablate_top__additional_AAAA_count             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407
   ablate_top__additional_A_count             37 65780    0 9183  7262   1.000000 0.441593 0.612646 0.497111             0.000000             0.558407

## 3. Confusion matrix 수치

In [1]:
# confusion_matrices
confusion_matrices

                                  feature_set    TN   FP   FN    TP
            ablate_top__additional_AAAA_count 65780    0 9183  7262
               ablate_top__additional_A_count 65780    0 9183  7262
ablate_top__additional_out_of_bailiwick_count 65780    0 9183  7262
                   ablate_top__answer_A_count 65780    0 9183  7262
              ablate_top__answer_record_count 65780    0 9183  7262
                 ablate_top__dns_count_add_rr 65780    0 9183  7262
                ablate_top__dns_count_answers 65780    0 9183  7262
                 ablate_top__has_additional_A 65780    0 9183  7262
                     ablate_top__record_total 65780    0 9183  7262
         ablate_top__unique_record_name_count 65780    0 9183  7262
              add_back_dropped__frame_cap_len 65780    0 9183  7262
                     add_back_dropped__ip_len 65780    0 9183  7262
              add_back_dropped__query_entropy 65780    0 9183  7262
          add_back_dropped__query_label_count 65780    0 9183  7262
             add_back_dropped__query_name_len 65780    0 9183  7262
                   add_back_dropped__src_port 65318  462 4183 12262
                    add_back_dropped__ttl_max 65780    0 9183  7262
                   add_back_dropped__ttl_mean 65780    0 9183  7262
                    add_back_dropped__ttl_min 65780    0 9183  7262
                 add_back_dropped__udp_length 65780    0 9183  7262
                                  all_current 65780    0 9183  7262
                           dns_structure_only 65780    0 9183  7262
                        dropped_shortcut_only 60715 5065    0 16445
                       shortcut_suspects_only 64661 1119 3428 13017
                          top_importance_only 65780    0 9183  7262

## 4. TP/FN 분리 통계 상위

In [1]:
# tp_fn_statistics
tp_fn_statistics

                                  feature_set                  feature comparison left_group right_group  mann_whitney_u_pvalue  cohens_d  separation_score  left_count  left_mean  left_median  left_std  left_min  left_max  left_q25  left_q75  left_IQR  left_missing_count  left_zero_ratio  left_unique_count  right_count  right_mean  right_median  right_std  right_min  right_max  right_q25  right_q75  right_IQR  right_missing_count  right_zero_ratio  right_unique_count
                                  all_current         has_additional_A   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                                  all_current         has_additional_A   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                                  all_current       additional_A_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                                  all_current       additional_A_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                                  all_current unique_record_name_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        2.0          2.0       0.0       2.0       2.0       2.0       2.0       0.0                   0              0.0                  1         9183         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                                  all_current unique_record_name_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         7262         2.0           2.0        0.0        2.0        2.0        2.0        2.0        0.0                    0               0.0                   1
                                  all_current         dns_count_add_rr   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                                  all_current         dns_count_add_rr   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                          top_importance_only         has_additional_A   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                          top_importance_only         has_additional_A   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                          top_importance_only       additional_A_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                          top_importance_only       additional_A_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                          top_importance_only unique_record_name_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        2.0          2.0       0.0       2.0       2.0       2.0       2.0       0.0                   0              0.0                  1         9183         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                          top_importance_only unique_record_name_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         7262         2.0           2.0        0.0        2.0        2.0        2.0        2.0        0.0                    0               0.0                   1
                          top_importance_only         dns_count_add_rr   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                          top_importance_only         dns_count_add_rr   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                           dns_structure_only         has_additional_A   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                           dns_structure_only         has_additional_A   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                           dns_structure_only       additional_A_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                           dns_structure_only       additional_A_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                           dns_structure_only unique_record_name_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        2.0          2.0       0.0       2.0       2.0       2.0       2.0       0.0                   0              0.0                  1         9183         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                           dns_structure_only unique_record_name_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         7262         2.0           2.0        0.0        2.0        2.0        2.0        2.0        0.0                    0               0.0                   1
                           dns_structure_only         dns_count_add_rr   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                           dns_structure_only         dns_count_add_rr   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                 ablate_top__has_additional_A       additional_A_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                 ablate_top__has_additional_A       additional_A_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                 ablate_top__has_additional_A unique_record_name_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        2.0          2.0       0.0       2.0       2.0       2.0       2.0       0.0                   0              0.0                  1         9183         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
                 ablate_top__has_additional_A unique_record_name_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         7262         2.0           2.0        0.0        2.0        2.0        2.0        2.0        0.0                    0               0.0                   1
                 ablate_top__has_additional_A         dns_count_add_rr   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
                 ablate_top__has_additional_A         dns_count_add_rr   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
               ablate_top__additional_A_count         has_additional_A   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
               ablate_top__additional_A_count         has_additional_A   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
               ablate_top__additional_A_count unique_record_name_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        2.0          2.0       0.0       2.0       2.0       2.0       2.0       0.0                   0              0.0                  1         9183         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
               ablate_top__additional_A_count unique_record_name_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         7262         2.0           2.0        0.0        2.0        2.0        2.0        2.0        0.0                    0               0.0                   1
               ablate_top__additional_A_count         dns_count_add_rr   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
               ablate_top__additional_A_count         dns_count_add_rr   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
         ablate_top__unique_record_name_count         has_additional_A   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
         ablate_top__unique_record_name_count         has_additional_A   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
         ablate_top__unique_record_name_count       additional_A_count   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1
         ablate_top__unique_record_name_count       additional_A_count   FN_vs_TP         FN          TP                    0.0       NaN      1000000000.0        9183        0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0                   0              1.0                  1         7262         1.0           1.0        0.0        1.0        1.0        1.0        1.0        0.0                    0               0.0                   1
         ablate_top__unique_record_name_count         dns_count_add_rr   TP_vs_FN         TP          FN                    0.0       NaN      1000000000.0        7262        1.0          1.0       0.0       1.0       1.0       1.0       1.0       0.0                   0              0.0                  1         9183         0.0           0.0        0.0        0.0        0.0        0.0        0.0        0.0                    0               1.0                   1

## 5. TN/FP 분리 통계 상위

In [1]:
# tn_fp_statistics
tn_fp_statistics

                 feature_set                           feature comparison left_group right_group  mann_whitney_u_pvalue  cohens_d  separation_score  left_count    left_mean  left_median     left_std   left_min     left_max     left_q25     left_q75     left_IQR  left_missing_count  left_zero_ratio  left_unique_count  right_count   right_mean  right_median    right_std  right_min    right_max  right_q25    right_q75    right_IQR  right_missing_count  right_zero_ratio  right_unique_count
       dropped_shortcut_only                          src_port   TN_vs_FP         TN          FP           0.000000e+00 17.882531      3.000000e+13       60715 29951.707074 30053.000000  1740.280841  53.000000 30053.000000 30053.000000 30053.000000     0.000000                   0         0.000000                  2         5065    53.000000     53.000000     0.000000       53.0    53.000000  53.000000    53.000000     0.000000                    0          0.000000                   1
      shortcut_suspects_only                          src_port   TN_vs_FP         TN          FP           0.000000e+00  3.850848      3.000000e+13       64661 28127.109587 30053.000000  7353.128225  53.000000 30053.000000 30053.000000 30053.000000     0.000000                   0         0.000000                  2         1119    53.000000     53.000000     0.000000       53.0    53.000000  53.000000    53.000000     0.000000                    0          0.000000                   1
  add_back_dropped__src_port                          src_port   TN_vs_FP         TN          FP           0.000000e+00  3.560043      3.000000e+13       65318 27844.726630 30053.000000  7834.071064  53.000000 30053.000000 30053.000000 30053.000000     0.000000                   0         0.000000                  2          462    53.000000     53.000000     0.000000       53.0    53.000000  53.000000    53.000000     0.000000                    0          0.000000                   1
      shortcut_suspects_only                  dns_count_add_rr   TN_vs_FP         TN          FP           0.000000e+00  1.610175      1.000000e+09       64661     1.219684     1.000000     0.764006   0.000000     3.000000     1.000000     1.000000     0.000000                   0         0.064196                  3         1119     0.000000      0.000000     0.000000        0.0     0.000000   0.000000     0.000000     0.000000                    0          1.000000                   1
  add_back_dropped__src_port                  dns_count_add_rr   TN_vs_FP         TN          FP           0.000000e+00  1.573932      1.000000e+09       65318     1.207416     1.000000     0.769836   0.000000     3.000000     1.000000     1.000000     0.000000                   0         0.073609                  3          462     0.000000      0.000000     0.000000        0.0     0.000000   0.000000     0.000000     0.000000                    0          1.000000                   1
       dropped_shortcut_only                     query_entropy   TN_vs_FP         TN          FP           0.000000e+00  4.417581      1.865761e+00       60715     4.032203     4.004344     0.216353   3.130718     4.649878     3.883074     4.207212     0.324138                   0         0.000000               3363         5065     3.077728      2.947703     0.212550        2.0     3.914866   2.947703     3.189898     0.242195                    0          0.000000                 113
      shortcut_suspects_only                     query_entropy   TN_vs_FP         TN          FP           0.000000e+00  2.753275      1.574815e+00       64661     3.973438     3.993270     0.315892   2.555913     4.649878     3.852728     4.193252     0.340524                   0         0.000000               3450         1119     3.107599      3.026987     0.217483        2.0     3.914866   2.947703     3.220764     0.273061                    0          0.000000                  38
       dropped_shortcut_only                 query_label_count   TN_vs_FP         TN          FP           0.000000e+00  4.345386      1.500000e+00       60715     4.605600     5.000000     0.518138   3.000000     5.000000     4.000000     5.000000     1.000000                   0         0.000000                  3         5065     2.364462      2.000000     0.486225        1.0     4.000000   2.000000     3.000000     1.000000                    0          0.000000                   4
       dropped_shortcut_only                    query_name_len   TN_vs_FP         TN          FP           0.000000e+00  2.448364      1.090909e+00       60715    36.386330    33.000000    10.245466  16.000000    58.000000    27.000000    43.000000    16.000000                   0         0.000000                 43         5065    12.092004      9.000000     4.517544        4.0    39.000000   9.000000    15.000000     6.000000                    0          0.000000                  25
      shortcut_suspects_only                 query_label_count   TN_vs_FP         TN          FP           0.000000e+00  2.555445      1.000000e+00       64661     4.465613     5.000000     0.753041   1.000000     5.000000     4.000000     5.000000     1.000000                   0         0.000000                  5         1119     2.550492      3.000000     0.497666        2.0     3.000000   2.000000     3.000000     1.000000                    0          0.000000                   2
      shortcut_suspects_only                    query_name_len   TN_vs_FP         TN          FP           0.000000e+00  1.927171      8.695652e-01       64661    34.892625    33.000000    11.585372   8.000000    58.000000    26.000000    43.000000    17.000000                   0         0.000000                 51         1119    12.734584     13.000000     3.892814        4.0    23.000000   9.000000    15.000000     6.000000                    0          0.000000                  16
       dropped_shortcut_only                         frame_len   TN_vs_FP         TN          FP           0.000000e+00  1.096681      6.250000e-01       60715   177.757210   172.000000    29.706019 103.000000   291.000000   149.000000   197.000000    48.000000                   0         0.000000                 99         5065   145.526357    142.000000    25.287372       70.0   419.000000 142.000000   142.000000     0.000000                    0          0.000000                 128
       dropped_shortcut_only                            ip_len   TN_vs_FP         TN          FP           0.000000e+00  1.016882      6.250000e-01       60715   157.777469   152.000000    29.682589  89.000000   277.000000   129.000000   177.000000    48.000000                   0         0.000000                 95         5065   127.868312    122.000000    25.958122       56.0   405.000000 122.000000   122.000000     0.000000                    0          0.000000                 128
       dropped_shortcut_only                     frame_cap_len   TN_vs_FP         TN          FP           0.000000e+00  1.096681      6.250000e-01       60715   177.757210   172.000000    29.706019 103.000000   291.000000   149.000000   197.000000    48.000000                   0         0.000000                 99         5065   145.526357    142.000000    25.287372       70.0   419.000000 142.000000   142.000000     0.000000                    0          0.000000                 128
       dropped_shortcut_only                        udp_length   TN_vs_FP         TN          FP           0.000000e+00  1.016882      6.250000e-01       60715   137.777469   132.000000    29.682589  69.000000   257.000000   109.000000   157.000000    48.000000                   0         0.000000                 95         5065   107.868312    102.000000    25.958122       36.0   385.000000 102.000000   102.000000     0.000000                    0          0.000000                 128
      shortcut_suspects_only                         frame_len   TN_vs_FP         TN          FP           0.000000e+00  1.450024      6.101695e-01       64661   176.017816   172.000000    30.295474  71.000000   419.000000   148.000000   195.000000    47.000000                   0         0.000000                153         1119   132.378910    136.000000    14.372235       70.0   158.000000 130.000000   142.000000    12.000000                    0          0.000000                  34
      shortcut_suspects_only                     frame_cap_len   TN_vs_FP         TN          FP           0.000000e+00  1.450024      6.101695e-01       64661   176.017816   172.000000    30.295474  71.000000   419.000000   148.000000   195.000000    47.000000                   0         0.000000                153         1119   132.378910    136.000000    14.372235       70.0   158.000000 130.000000   142.000000    12.000000                    0          0.000000                  34
      shortcut_suspects_only                            ip_len   TN_vs_FP         TN          FP           0.000000e+00  1.343927      5.555556e-01       64661   156.160901   152.000000    30.235271  57.000000   405.000000   128.000000   176.000000    48.000000                   0         0.000000                146         1119   115.810545    122.000000    12.880899       56.0   144.000000 116.000000   122.000000     6.000000                    0          0.000000                  33
      shortcut_suspects_only                        udp_length   TN_vs_FP         TN          FP           0.000000e+00  1.343927      5.555556e-01       64661   136.160901   132.000000    30.235271  37.000000   385.000000   108.000000   156.000000    48.000000                   0         0.000000                146         1119    95.810545    102.000000    12.880899       36.0   124.000000  96.000000   102.000000     6.000000                    0          0.000000                  33
      shortcut_suspects_only                      record_total   TN_vs_FP         TN          FP          1.887301e-299  1.032252      0.000000e+00       64661     2.499265     2.000000     0.895561   0.000000    12.000000     2.000000     3.000000     1.000000                   0         0.000510                 13         1119     1.579088      2.000000     0.606133        0.0     3.000000   1.000000     2.000000     1.000000                    0          0.013405                   4
  add_back_dropped__src_port                         frame_len   TN_vs_FP         TN          FP          1.618560e-281  1.974206      7.808219e-01       65318   175.694372   172.000000    30.287255  70.000000   419.000000   148.000000   194.000000    46.000000                   0         0.000000                147          462   116.049784    115.000000    16.345235       84.0   159.000000 103.000000   130.000000    27.000000                    0          0.000000                  44
      shortcut_suspects_only                    answer_A_count   TN_vs_FP         TN          FP          6.783329e-159  0.644125      1.000000e+00       64661     0.700592     1.000000     0.736582   0.000000    11.000000     0.000000     1.000000     1.000000                   0         0.377121                 12         1119     0.228776      0.000000     0.434876        0.0     2.000000   0.000000     0.000000     0.000000                    0          0.777480                   3
  add_back_dropped__src_port                 dns_count_answers   TN_vs_FP         TN          FP           6.361344e-97 -0.553722      1.000000e+00       65318     1.274013     1.000000     0.690846   0.000000    12.000000     1.000000     1.000000     0.000000                   0         0.005557                 13          462     1.655844      2.000000     0.475607        1.0     2.000000   1.000000     2.000000     1.000000                    0          0.000000                   2
  add_back_dropped__src_port               answer_record_count   TN_vs_FP         TN          FP           6.361344e-97 -0.553722      1.000000e+00       65318     1.274013     1.000000     0.690846   0.000000    12.000000     1.000000     1.000000     0.000000                   0         0.005557                 13          462     1.655844      2.000000     0.475607        1.0     2.000000   1.000000     2.000000     1.000000                    0          0.000000                   2
  add_back_dropped__src_port                      record_total   TN_vs_FP         TN          FP           1.602868e-95  0.866172      0.000000e+00       65318     2.489069     2.000000     0.899344   0.000000    12.000000     2.000000     3.000000     1.000000                   0         0.000735                 13          462     1.712121      2.000000     0.453265        1.0     2.000000   1.000000     2.000000     1.000000                    0          0.000000                   2
      shortcut_suspects_only                 dns_count_answers   TN_vs_FP         TN          FP           1.098718e-90 -0.370995      0.000000e+00       64661     1.272343     1.000000     0.690733   0.000000    12.000000     1.000000     1.000000     0.000000                   0         0.005336                 13         1119     1.528150      1.000000     0.615006        0.0     3.000000   1.000000     2.000000     1.000000                    0          0.016086                   4
      shortcut_suspects_only               answer_record_count   TN_vs_FP         TN          FP           1.098718e-90 -0.370995      0.000000e+00       64661     1.272343     1.000000     0.690733   0.000000    12.000000     1.000000     1.000000     0.000000                   0         0.005336                 13         1119     1.528150      1.000000     0.615006        0.0     3.000000   1.000000     2.000000     1.000000                    0          0.016086                   4
  add_back_dropped__src_port          unique_record_name_count   TN_vs_FP         TN          FP           2.617601e-75 -0.836657      5.000000e-01       65318     1.314462     1.000000     0.475448   0.000000     5.000000     1.000000     2.000000     1.000000                   0         0.000765                  6          462     1.712121      2.000000     0.453265        1.0     2.000000   1.000000     2.000000     1.000000                    0          0.000000                   2
      shortcut_suspects_only                           ttl_max   TN_vs_FP         TN          FP           6.992294e-68 -0.869357      1.963982e-01       64661 15602.062743   300.000000 27460.245366  -1.000000 86400.000000   200.000000 21600.000000 21400.000000                   0         0.000000                723         1119 39720.548704  21413.000000 40891.868908       -1.0 86400.000000 299.000000 86400.000000 86101.000000                    0          0.000000                 413
      shortcut_suspects_only                          ttl_mean   TN_vs_FP         TN          FP           1.166635e-67 -1.135430      1.088084e-01       64661 12246.988739   300.000000 22638.494335  -1.000000 86400.000000   200.000000 10714.000000 10514.000000                   0         0.000000               1912         1119 38466.038576  10817.500000 41617.029448       -1.0 86400.000000 253.250000 86400.000000 86146.750000                    0          0.000000                 491
      shortcut_suspects_only          unique_record_name_count   TN_vs_FP         TN          FP           2.950128e-63 -0.547064      5.000000e-01       64661     1.312832     1.000000     0.472832   0.000000     5.000000     1.000000     2.000000     1.000000                   0         0.000541                  6         1119     1.572833      2.000000     0.599503        0.0     3.000000   1.000000     2.000000     1.000000                    0          0.013405                   4
       dropped_shortcut_only                           ttl_min   TN_vs_FP         TN          FP           3.218940e-48 -0.214290      1.536856e-02       60715  9847.994878   217.000000 22323.147902   1.000000 86400.000000   148.000000  3600.000000  3452.000000                   0         0.000000                285         5065 14710.015597    600.000000 26687.581380       -1.0 86400.000000 131.000000 21600.000000 21469.000000                    0          0.000000                 469
       dropped_shortcut_only                          ttl_mean   TN_vs_FP         TN          FP           1.071977e-42 -0.132692      4.693163e-02       60715 12454.695352   297.000000 23054.295955  10.000000 86400.000000   200.000000 10856.500000 10656.500000                   0         0.000000               1288         5065 15549.695505   1799.000000 26351.852496       -1.0 86400.000000 252.500000 21600.000000 21347.500000                    0          0.000000                1190
      shortcut_suspects_only                  has_additional_A   TN_vs_FP         TN          FP           4.840456e-42  0.410217      0.000000e+00       64661     0.141940     0.000000     0.348992   0.000000     1.000000     0.000000     0.000000     0.000000                   0         0.858060                  2         1119     0.000000      0.000000     0.000000        0.0     0.000000   0.000000     0.000000     0.000000                    0          1.000000                   1
      shortcut_suspects_only                additional_A_count   TN_vs_FP         TN          FP           4.840456e-42  0.410217      0.000000e+00       64661     0.141940     0.000000     0.348992   0.000000     1.000000     0.000000     0.000000     0.000000                   0         0.858060                  2         1119     0.000000      0.000000     0.000000        0.0     0.000000   0.000000     0.000000     0.000000                    0          1.000000                   1
      shortcut_suspects_only             additional_AAAA_count   TN_vs_FP         TN          FP           4.840456e-42  0.410217      0.000000e+00       64661     0.141940     0.000000     0.348992   0.000000     1.000000     0.000000     0.000000     0.000000                   0         0.858060                  2         1119     0.000000      0.000000     0.000000        0.0     0.000000   0.000000     0.000000     0.000000                    0          1.000000                   1
      shortcut_suspects_only additional_out_of_bailiwick_count   TN_vs_FP         TN          FP           9.231143e-42  0.408783      0.000000e+00       64661     0.282179     0.000000     0.696233   0.000000     2.000000     0.000000     0.000000     0.000000                   0         0.858910                  2         1119     0.000000      0.000000     0.000000        0.0     0.000000   0.000000     0.000000     0.000000                    0          1.000000                   1
       dropped_shortcut_only                           ttl_max   TN_vs_FP         TN          FP           6.537124e-38 -0.043921      6.394886e-02       60715 15917.940377   300.000000 28055.483814  10.000000 86400.000000   200.000000 21600.000000 21400.000000                   0         0.000000                302         5065 17144.032182   3031.000000 26182.619503       -1.0 86400.000000 294.000000 21600.000000 21306.000000                    0          0.000000                 828
      shortcut_suspects_only                           ttl_min   TN_vs_FP         TN          FP           1.483358e-33 -1.223216      3.577997e-03       64661  9755.281081   218.000000 21936.741108  -1.000000 86400.000000   148.000000  3600.000000  3452.000000                   0         0.000000                399         1119 37212.697051    539.000000 42584.347511       -1.0 86400.000000 137.000000 86400.000000 86263.000000                    0          0.000000                 310

## 6. Probability 요약

In [1]:
# probability_summary
probability_summary

                                  feature_set         group  count     mean   median          std      min      max      q25      q75      IQR
                                  all_current actual_normal  65780 0.004956 0.003675 1.694408e-02 0.000000 0.214846 0.000000 0.004084 0.004084
                                  all_current actual_attack  16445 0.342159 0.043675 3.817926e-01 0.003675 0.993673 0.043675 0.592909 0.549235
                                  all_current            TP   7262 0.740568 0.592909 2.127383e-01 0.522910 0.993673 0.527910 0.988673 0.460763
                                  all_current            FN   9183 0.027094 0.043675 2.113004e-02 0.003675 0.069213 0.003675 0.043675 0.040000
                                  all_current            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                                  all_current            TN  65780 0.004956 0.003675 1.694408e-02 0.000000 0.214846 0.000000 0.004084 0.004084
                        dropped_shortcut_only actual_normal  65780 0.038342 0.000000 1.368948e-01 0.000000 0.930000 0.000000 0.000000 0.000000
                        dropped_shortcut_only actual_attack  16445 0.532059 0.485000 1.769517e-01 0.395000 1.000000 0.470000 0.485000 0.015000
                        dropped_shortcut_only            TP  16445 0.532059 0.485000 1.769517e-01 0.395000 1.000000 0.470000 0.485000 0.015000
                        dropped_shortcut_only            FN      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                        dropped_shortcut_only            FP   5065 0.487228 0.470000 1.491465e-01 0.310000 0.930000 0.405000 0.470000 0.065000
                        dropped_shortcut_only            TN  60715 0.000894 0.000000 1.536386e-02 0.000000 0.295000 0.000000 0.000000 0.000000
                          top_importance_only actual_normal  65780 0.001187 0.000000 1.061549e-02 0.000000 0.125000 0.000000 0.000000 0.000000
                          top_importance_only actual_attack  16445 0.374443 0.000000 4.333292e-01 0.000000 1.000000 0.000000 0.845000 0.845000
                          top_importance_only            TP   7262 0.847937 0.845000 1.539635e-01 0.625000 1.000000 0.625000 1.000000 0.375000
                          top_importance_only            FN   9183 0.000000 0.000000 0.000000e+00 0.000000 0.000000 0.000000 0.000000 0.000000
                          top_importance_only            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                          top_importance_only            TN  65780 0.001187 0.000000 1.061549e-02 0.000000 0.125000 0.000000 0.000000 0.000000
                           dns_structure_only actual_normal  65780 0.000480 0.000000 4.606549e-03 0.000000 0.065000 0.000000 0.000000 0.000000
                           dns_structure_only actual_attack  16445 0.358784 0.000000 4.188438e-01 0.000000 1.000000 0.000000 0.750000 0.750000
                           dns_structure_only            TP   7262 0.812476 0.750000 1.692110e-01 0.600000 1.000000 0.600000 1.000000 0.400000
                           dns_structure_only            FN   9183 0.000000 0.000000 0.000000e+00 0.000000 0.000000 0.000000 0.000000 0.000000
                           dns_structure_only            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                           dns_structure_only            TN  65780 0.000480 0.000000 4.606549e-03 0.000000 0.065000 0.000000 0.000000 0.000000
                       shortcut_suspects_only actual_normal  65780 0.022706 0.000000 7.877007e-02 0.000000 0.450000 0.000000 0.000000 0.000000
                       shortcut_suspects_only actual_attack  16445 0.438745 0.460000 1.746345e-01 0.265000 0.999983 0.310000 0.520000 0.210000
                       shortcut_suspects_only            TP  13017 0.484501 0.464984 1.687753e-01 0.310000 0.999983 0.310000 0.604984 0.294984
                       shortcut_suspects_only            FN   3428 0.265000 0.265000 5.551925e-17 0.265000 0.265000 0.265000 0.265000 0.000000
                       shortcut_suspects_only            FP   1119 0.377126 0.369996 6.565721e-02 0.300000 0.450000 0.317496 0.450000 0.132504
                       shortcut_suspects_only            TN  64661 0.016572 0.000000 6.345151e-02 0.000000 0.299996 0.000000 0.000000 0.000000
                 ablate_top__has_additional_A actual_normal  65780 0.008935 0.006445 1.902039e-02 0.000000 0.241877 0.005825 0.008164 0.002339
                 ablate_top__has_additional_A actual_attack  16445 0.343790 0.130849 3.503504e-01 0.002914 0.990615 0.125849 0.517704 0.391855
                 ablate_top__has_additional_A            TP   7262 0.683554 0.517704 2.566937e-01 0.410765 0.990615 0.415766 0.980640 0.564874
                 ablate_top__has_additional_A            FN   9183 0.075102 0.125849 6.493216e-02 0.002914 0.171992 0.002914 0.125849 0.122935
                 ablate_top__has_additional_A            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                 ablate_top__has_additional_A            TN  65780 0.008935 0.006445 1.902039e-02 0.000000 0.241877 0.005825 0.008164 0.002339
               ablate_top__additional_A_count actual_normal  65780 0.006841 0.004069 1.498498e-02 0.000000 0.200988 0.000000 0.009861 0.009861
               ablate_top__additional_A_count actual_attack  16445 0.339894 0.112850 3.502038e-01 0.003521 0.979628 0.103921 0.529044 0.425123
               ablate_top__additional_A_count            TP   7262 0.689479 0.529044 2.358568e-01 0.443024 0.979628 0.448025 0.959719 0.511694
               ablate_top__additional_A_count            FN   9183 0.063440 0.103921 5.059297e-02 0.003521 0.131523 0.007384 0.103921 0.096538
               ablate_top__additional_A_count            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
               ablate_top__additional_A_count            TN  65780 0.006841 0.004069 1.498498e-02 0.000000 0.200988 0.000000 0.009861 0.009861
         ablate_top__unique_record_name_count actual_normal  65780 0.002585 0.000000 1.009588e-02 0.000000 0.157517 0.000000 0.000622 0.000622
         ablate_top__unique_record_name_count actual_attack  16445 0.368517 0.125000 3.676151e-01 0.000000 0.998956 0.125000 0.623956 0.498956
         ablate_top__unique_record_name_count            TP   7262 0.744786 0.623956 2.176706e-01 0.493956 0.998956 0.498956 0.993956 0.495000
         ablate_top__unique_record_name_count            FN   9183 0.070961 0.125000 6.350207e-02 0.000000 0.157517 0.000000 0.125000 0.125000
         ablate_top__unique_record_name_count            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
         ablate_top__unique_record_name_count            TN  65780 0.002585 0.000000 1.009588e-02 0.000000 0.157517 0.000000 0.000622 0.000622
ablate_top__additional_out_of_bailiwick_count actual_normal  65780 0.002979 0.000363 1.037545e-02 0.000000 0.130361 0.000000 0.001761 0.001761
ablate_top__additional_out_of_bailiwick_count actual_attack  16445 0.344182 0.020363 3.969620e-01 0.000363 0.995714 0.020363 0.658954 0.638591
ablate_top__additional_out_of_bailiwick_count            TP   7262 0.764248 0.658954 2.017207e-01 0.528952 0.995714 0.528954 0.994317 0.465363
ablate_top__additional_out_of_bailiwick_count            FN   9183 0.011989 0.020363 1.034764e-02 0.000363 0.050530 0.000363 0.020363 0.020000
ablate_top__additional_out_of_bailiwick_count            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
ablate_top__additional_out_of_bailiwick_count            TN  65780 0.002979 0.000363 1.037545e-02 0.000000 0.130361 0.000000 0.001761 0.001761
                     ablate_top__record_total actual_normal  65780 0.005528 0.003393 1.126015e-02 0.000000 0.153898 0.003181 0.003909 0.000727
                     ablate_top__record_total actual_attack  16445 0.368161 0.073609 3.898671e-01 0.000000 0.996555 0.063181 0.733809 0.670627
                     ablate_top__record_total            TP   7262 0.782424 0.733809 1.877143e-01 0.524777 0.996555 0.536552 0.981775 0.445223
                     ablate_top__record_total            FN   9183 0.040559 0.066064 3.580105e-02 0.000000 0.091536 0.000428 0.073609 0.073181
                     ablate_top__record_total            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                     ablate_top__record_total            TN  65780 0.005528 0.003393 1.126015e-02 0.000000 0.153898 0.003181 0.003909 0.000727
                   ablate_top__answer_A_count actual_normal  65780 0.005344 0.003512 1.616535e-02 0.000000 0.195272 0.003026 0.004475 0.001449
                   ablate_top__answer_A_count actual_attack  16445 0.376606 0.068770 3.913619e-01 0.003770 0.992607 0.063770 0.722707 0.658936
                   ablate_top__answer_A_count            TP   7262 0.800982 0.727706 1.513542e-01 0.625498 0.992607 0.632494 0.968240 0.335746
                   ablate_top__answer_A_count            FN   9183 0.041005 0.068770 3.329104e-02 0.003770 0.085287 0.003770 0.068770 0.065000
                   ablate_top__answer_A_count            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                   ablate_top__answer_A_count            TN  65780 0.005344 0.003512 1.616535e-02 0.000000 0.195272 0.003026 0.004475 0.001449
                 ablate_top__dns_count_add_rr actual_normal  65780 0.006444 0.003609 1.311963e-02 0.000000 0.192767 0.003183 0.007816 0.004634
                 ablate_top__dns_count_add_rr actual_attack  16445 0.361595 0.088609 3.756971e-01 0.000373 0.996557 0.073181 0.638811 0.565629
                 ablate_top__dns_count_add_rr            TP   7262 0.756212 0.638811 1.963816e-01 0.531773 0.996557 0.541773 0.980984 0.439211
                 ablate_top__dns_count_add_rr            FN   9183 0.049529 0.081064 4.157443e-02 0.000373 0.110542 0.004635 0.087816 0.083181
                 ablate_top__dns_count_add_rr            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                 ablate_top__dns_count_add_rr            TN  65780 0.006444 0.003609 1.311963e-02 0.000000 0.192767 0.003183 0.007816 0.004634
                ablate_top__dns_count_answers actual_normal  65780 0.004698 0.002444 1.438052e-02 0.000000 0.209424 0.001023 0.004124 0.003101
                ablate_top__dns_count_answers actual_attack  16445 0.356030 0.081239 3.746027e-01 0.000428 0.990452 0.075561 0.603809 0.528249
                ablate_top__dns_count_answers            TP   7262 0.749129 0.603809 1.975532e-01 0.551596 0.990452 0.558591 0.979620 0.421029
                ablate_top__dns_count_answers            FN   9183 0.045164 0.077073 3.982421e-02 0.000428 0.108948 0.000428 0.081239 0.080811
                ablate_top__dns_count_answers            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                ablate_top__dns_count_answers            TN  65780 0.004698 0.002444 1.438052e-02 0.000000 0.209424 0.001023 0.004124 0.003101
            ablate_top__additional_AAAA_count actual_normal  65780 0.003168 0.001043 9.765132e-03 0.000000 0.131040 0.000000 0.001663 0.001663
            ablate_top__additional_AAAA_count actual_attack  16445 0.353336 0.050000 3.897738e-01 0.000000 0.998954 0.050000 0.663955 0.613955
            ablate_top__additional_AAAA_count            TP   7262 0.764212 0.663955 2.022111e-01 0.518955 0.998954 0.528955 0.993955 0.465000
            ablate_top__additional_AAAA_count            FN   9183 0.028410 0.050000 2.525970e-02 0.000000 0.068261 0.000000 0.050000 0.050000
            ablate_top__additional_AAAA_count            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
            ablate_top__additional_AAAA_count            TN  65780 0.003168 0.001043 9.765132e-03 0.000000 0.131040 0.000000 0.001663 0.001663
              ablate_top__answer_record_count actual_normal  65780 0.005982 0.003909 1.456015e-02 0.000000 0.198907 0.003181 0.005013 0.001832
              ablate_top__answer_record_count actual_attack  16445 0.356440 0.068609 3.802209e-01 0.000000 0.993387 0.063609 0.633597 0.569987
              ablate_top__answer_record_count            TP   7262 0.758592 0.633597 1.904990e-01 0.556774 0.993387 0.566773 0.976990 0.410218
              ablate_top__answer_record_count            FN   9183 0.038415 0.068609 3.390020e-02 0.000000 0.086216 0.000428 0.068609 0.068181
              ablate_top__answer_record_count            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
              ablate_top__answer_record_count            TN  65780 0.005982 0.003909 1.456015e-02 0.000000 0.198907 0.003181 0.005013 0.001832
                     add_back_dropped__ip_len actual_normal  65780 0.002591 0.000000 1.847333e-02 0.000000 0.210000 0.000000 0.000000 0.000000
                     add_back_dropped__ip_len actual_attack  16445 0.347035 0.115000 3.560923e-01 0.000000 0.999999 0.115000 0.504999 0.389999
                     add_back_dropped__ip_len            TP   7262 0.701894 0.504999 2.388978e-01 0.484998 0.999999 0.489998 0.974999 0.485001
                     add_back_dropped__ip_len            FN   9183 0.066409 0.115000 6.003193e-02 0.000000 0.155000 0.000000 0.115000 0.115000
                     add_back_dropped__ip_len            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                     add_back_dropped__ip_len            TN  65780 0.002591 0.000000 1.847333e-02 0.000000 0.210000 0.000000 0.000000 0.000000
              add_back_dropped__frame_cap_len actual_normal  65780 0.002765 0.000000 1.980248e-02 0.000000 0.210000 0.000000 0.000000 0.000000
              add_back_dropped__frame_cap_len actual_attack  16445 0.347035 0.115000 3.560923e-01 0.000000 0.999999 0.115000 0.504999 0.389999
              add_back_dropped__frame_cap_len            TP   7262 0.701894 0.504999 2.388978e-01 0.484998 0.999999 0.489998 0.974999 0.485001
              add_back_dropped__frame_cap_len            FN   9183 0.066409 0.115000 6.003193e-02 0.000000 0.155000 0.000000 0.115000 0.115000
              add_back_dropped__frame_cap_len            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
              add_back_dropped__frame_cap_len            TN  65780 0.002765 0.000000 1.980248e-02 0.000000 0.210000 0.000000 0.000000 0.000000
                 add_back_dropped__udp_length actual_normal  65780 0.002591 0.000000 1.847333e-02 0.000000 0.210000 0.000000 0.000000 0.000000
                 add_back_dropped__udp_length actual_attack  16445 0.347035 0.115000 3.560923e-01 0.000000 0.999999 0.115000 0.504999 0.389999
                 add_back_dropped__udp_length            TP   7262 0.701894 0.504999 2.388978e-01 0.484998 0.999999 0.489998 0.974999 0.485001
                 add_back_dropped__udp_length            FN   9183 0.066409 0.115000 6.003193e-02 0.000000 0.155000 0.000000 0.115000 0.115000
                 add_back_dropped__udp_length            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                 add_back_dropped__udp_length            TN  65780 0.002591 0.000000 1.847333e-02 0.000000 0.210000 0.000000 0.000000 0.000000
                   add_back_dropped__src_port actual_normal  65780 0.019036 0.000000 6.393069e-02 0.000000 0.370000 0.000000 0.001893 0.001893
                   add_back_dropped__src_port actual_attack  16445 0.514067 0.320000 2.747031e-01 0.235000 0.999998 0.288547 0.669999 0.381451
                   add_back_dropped__src_port            TP  12262 0.600298 0.629999 2.682200e-01 0.300000 0.999998 0.320000 0.716885 0.396885
                   add_back_dropped__src_port            FN   4183 0.261290 0.265000 9.231312e-03 0.235000 0.298547 0.260000 0.265000 0.005000
                   add_back_dropped__src_port            FP    462 0.314997 0.306893 1.752635e-02 0.300000 0.370000 0.300000 0.321893 0.021893
                   add_back_dropped__src_port            TN  65318 0.016942 0.000000 5.907561e-02 0.000000 0.298547 0.000000 0.001893 0.001893
             add_back_dropped__query_name_len actual_normal  65780 0.005498 0.000000 2.120956e-02 0.000000 0.222370 0.000000 0.000622 0.000622
             add_back_dropped__query_name_len actual_attack  16445 0.386399 0.137370 3.455558e-01 0.050035 0.997320 0.118582 0.599917 0.481335
             add_back_dropped__query_name_len            TP   7262 0.744167 0.599917 1.984484e-01 0.544626 0.997320 0.544983 0.972320 0.427338
             add_back_dropped__query_name_len            FN   9183 0.103473 0.137370 3.764191e-02 0.050035 0.150039 0.062370 0.137370 0.075000
             add_back_dropped__query_name_len            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
             add_back_dropped__query_name_len            TN  65780 0.005498 0.000000 2.120956e-02 0.000000 0.222370 0.000000 0.000622 0.000622
              add_back_dropped__query_entropy actual_normal  65780 0.006507 0.000000 2.398750e-02 0.000000 0.254566 0.000000 0.000622 0.000622
              add_back_dropped__query_entropy actual_attack  16445 0.404593 0.144576 3.439818e-01 0.070000 0.999532 0.144576 0.641814 0.497238
              add_back_dropped__query_entropy            TP   7262 0.766443 0.641814 1.794569e-01 0.581814 0.999532 0.589324 0.971814 0.382490
              add_back_dropped__query_entropy            FN   9183 0.118439 0.144576 3.144186e-02 0.070000 0.174529 0.084576 0.144576 0.060000
              add_back_dropped__query_entropy            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
              add_back_dropped__query_entropy            TN  65780 0.006507 0.000000 2.398750e-02 0.000000 0.254566 0.000000 0.000622 0.000622
          add_back_dropped__query_label_count actual_normal  65780 0.004779 0.000000 1.940268e-02 0.000000 0.205000 0.000000 0.000622 0.000622
          add_back_dropped__query_label_count actual_attack  16445 0.378880 0.119953 3.567258e-01 0.040000 0.999952 0.115000 0.614999 0.499999
          add_back_dropped__query_label_count            TP   7262 0.751388 0.614999 1.943535e-01 0.544983 0.999952 0.555000 0.974999 0.420000
          add_back_dropped__query_label_count            FN   9183 0.084298 0.115000 3.863456e-02 0.040000 0.149905 0.040000 0.115000 0.075000
          add_back_dropped__query_label_count            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
          add_back_dropped__query_label_count            TN  65780 0.004779 0.000000 1.940268e-02 0.000000 0.205000 0.000000 0.000622 0.000622
                   add_back_dropped__ttl_mean actual_normal  65780 0.002685 0.000000 1.319113e-02 0.000000 0.223777 0.000000 0.000000 0.000000
                   add_back_dropped__ttl_mean actual_attack  16445 0.268168 0.055000 2.899175e-01 0.000000 0.988434 0.043547 0.414999 0.371452
                   add_back_dropped__ttl_mean            TP   7262 0.566225 0.572827 1.739618e-01 0.394998 0.988434 0.409999 0.694999 0.285000
                   add_back_dropped__ttl_mean            FN   9183 0.032461 0.050000 2.778121e-02 0.000000 0.120502 0.000000 0.050000 0.050000
                   add_back_dropped__ttl_mean            FP      0      NaN      NaN          NaN      NaN      NaN      NaN      NaN      NaN
                   add_back_dropped__ttl_mean            TN  65780 0.002685 0.000000 1.319113e-02 0.000000 0.223777 0.000000 0.000000 0.000000

## 7. Feature importance 상위

In [1]:
# top_feature_importances
top_feature_importances

                                  feature_set                           feature  importance
            ablate_top__additional_AAAA_count                additional_A_count    0.251033
            ablate_top__additional_AAAA_count                  has_additional_A    0.207953
            ablate_top__additional_AAAA_count additional_out_of_bailiwick_count    0.143456
            ablate_top__additional_AAAA_count          unique_record_name_count    0.094775
            ablate_top__additional_AAAA_count                         frame_len    0.084803
            ablate_top__additional_AAAA_count                            dns_id    0.040810
            ablate_top__additional_AAAA_count                    answer_A_count    0.039483
            ablate_top__additional_AAAA_count                      record_total    0.037776
            ablate_top__additional_AAAA_count                           ttl_std    0.027810
            ablate_top__additional_AAAA_count           additional_record_count    0.022555
            ablate_top__additional_AAAA_count                  dns_count_add_rr    0.016477
            ablate_top__additional_AAAA_count               answer_record_count    0.013984
            ablate_top__additional_AAAA_count                 dns_count_answers    0.007267
            ablate_top__additional_AAAA_count                answer_CNAME_count    0.006783
            ablate_top__additional_AAAA_count                 answer_AAAA_count    0.004190
               ablate_top__additional_A_count                  has_additional_A    0.268283
               ablate_top__additional_A_count additional_out_of_bailiwick_count    0.184631
               ablate_top__additional_A_count          unique_record_name_count    0.172213
               ablate_top__additional_A_count                         frame_len    0.108082
               ablate_top__additional_A_count                            dns_id    0.068416
               ablate_top__additional_A_count                    answer_A_count    0.041262
               ablate_top__additional_A_count                      record_total    0.040158
               ablate_top__additional_A_count                           ttl_std    0.030164
               ablate_top__additional_A_count               answer_record_count    0.019559
               ablate_top__additional_A_count             additional_AAAA_count    0.014031
               ablate_top__additional_A_count           additional_record_count    0.013475
               ablate_top__additional_A_count                 dns_count_answers    0.011547
               ablate_top__additional_A_count                  dns_count_add_rr    0.011087
               ablate_top__additional_A_count                answer_CNAME_count    0.009945
               ablate_top__additional_A_count                 answer_AAAA_count    0.006035
ablate_top__additional_out_of_bailiwick_count                additional_A_count    0.267507
ablate_top__additional_out_of_bailiwick_count                  has_additional_A    0.219378
ablate_top__additional_out_of_bailiwick_count          unique_record_name_count    0.161936
ablate_top__additional_out_of_bailiwick_count                         frame_len    0.109909
ablate_top__additional_out_of_bailiwick_count                            dns_id    0.051589
ablate_top__additional_out_of_bailiwick_count                    answer_A_count    0.038975
ablate_top__additional_out_of_bailiwick_count                      record_total    0.036866
ablate_top__additional_out_of_bailiwick_count                           ttl_std    0.025916
ablate_top__additional_out_of_bailiwick_count             additional_AAAA_count    0.020118
ablate_top__additional_out_of_bailiwick_count                  dns_count_add_rr    0.015389
ablate_top__additional_out_of_bailiwick_count               answer_record_count    0.014824
ablate_top__additional_out_of_bailiwick_count           additional_record_count    0.012428
ablate_top__additional_out_of_bailiwick_count                answer_CNAME_count    0.009716
ablate_top__additional_out_of_bailiwick_count                 dns_count_answers    0.007807
ablate_top__additional_out_of_bailiwick_count                 answer_AAAA_count    0.006854
                   ablate_top__answer_A_count                additional_A_count    0.206619
                   ablate_top__answer_A_count                  has_additional_A    0.193551
                   ablate_top__answer_A_count additional_out_of_bailiwick_count    0.143651
                   ablate_top__answer_A_count          unique_record_name_count    0.133125
                   ablate_top__answer_A_count                         frame_len    0.084920
                   ablate_top__answer_A_count                            dns_id    0.054433
                   ablate_top__answer_A_count                      record_total    0.045567
                   ablate_top__answer_A_count                           ttl_std    0.035183
                   ablate_top__answer_A_count                  dns_count_add_rr    0.024673
                   ablate_top__answer_A_count             additional_AAAA_count    0.019733
                   ablate_top__answer_A_count           additional_record_count    0.016808
                   ablate_top__answer_A_count               answer_record_count    0.013013
                   ablate_top__answer_A_count                 dns_count_answers    0.012965
                   ablate_top__answer_A_count                 answer_AAAA_count    0.008611
                   ablate_top__answer_A_count                answer_CNAME_count    0.006637
              ablate_top__answer_record_count                additional_A_count    0.216143
              ablate_top__answer_record_count                  has_additional_A    0.183607
              ablate_top__answer_record_count          unique_record_name_count    0.140697
              ablate_top__answer_record_count additional_out_of_bailiwick_count    0.135512
              ablate_top__answer_record_count                         frame_len    0.076356
              ablate_top__answer_record_count                            dns_id    0.054662
              ablate_top__answer_record_count                    answer_A_count    0.040135
              ablate_top__answer_record_count                      record_total    0.034015
              ablate_top__answer_record_count                           ttl_std    0.031188
              ablate_top__answer_record_count                  dns_count_add_rr    0.022600
              ablate_top__answer_record_count             additional_AAAA_count    0.019415
              ablate_top__answer_record_count                 dns_count_answers    0.016068
              ablate_top__answer_record_count           additional_record_count    0.012475
              ablate_top__answer_record_count                answer_CNAME_count    0.008408
              ablate_top__answer_record_count                 answer_AAAA_count    0.007733
                 ablate_top__dns_count_add_rr                additional_A_count    0.202042
                 ablate_top__dns_count_add_rr                  has_additional_A    0.190933
                 ablate_top__dns_count_add_rr          unique_record_name_count    0.143591
                 ablate_top__dns_count_add_rr additional_out_of_bailiwick_count    0.133480
                 ablate_top__dns_count_add_rr                         frame_len    0.076905
                 ablate_top__dns_count_add_rr                            dns_id    0.060082
                 ablate_top__dns_count_add_rr                    answer_A_count    0.045606
                 ablate_top__dns_count_add_rr                      record_total    0.036332
                 ablate_top__dns_count_add_rr                           ttl_std    0.033524
                 ablate_top__dns_count_add_rr             additional_AAAA_count    0.022254
                 ablate_top__dns_count_add_rr           additional_record_count    0.017366
                 ablate_top__dns_count_add_rr                 dns_count_answers    0.015640
                 ablate_top__dns_count_add_rr               answer_record_count    0.008570
                 ablate_top__dns_count_add_rr                 answer_AAAA_count    0.006677
                 ablate_top__dns_count_add_rr                answer_CNAME_count    0.006032
                ablate_top__dns_count_answers                additional_A_count    0.207459
                ablate_top__dns_count_answers                  has_additional_A    0.198016
                ablate_top__dns_count_answers additional_out_of_bailiwick_count    0.137310
                ablate_top__dns_count_answers          unique_record_name_count    0.129936
                ablate_top__dns_count_answers                         frame_len    0.077075
                ablate_top__dns_count_answers                            dns_id    0.059255
                ablate_top__dns_count_answers                    answer_A_count    0.040372
                ablate_top__dns_count_answers                      record_total    0.036927
                ablate_top__dns_count_answers                           ttl_std    0.033615
                ablate_top__dns_count_answers             additional_AAAA_count    0.021294
                ablate_top__dns_count_answers                  dns_count_add_rr    0.019993
                ablate_top__dns_count_answers               answer_record_count    0.012260
                ablate_top__dns_count_answers           additional_record_count    0.011928
                ablate_top__dns_count_answers                answer_CNAME_count    0.007070
                ablate_top__dns_count_answers                 answer_AAAA_count    0.006200
                 ablate_top__has_additional_A                additional_A_count    0.275496
                 ablate_top__has_additional_A          unique_record_name_count    0.181013
                 ablate_top__has_additional_A additional_out_of_bailiwick_count    0.164495
                 ablate_top__has_additional_A                         frame_len    0.122169
                 ablate_top__has_additional_A                            dns_id    0.061900
                 ablate_top__has_additional_A                      record_total    0.040728
                 ablate_top__has_additional_A                           ttl_std    0.036047
                 ablate_top__has_additional_A                    answer_A_count    0.034218
                 ablate_top__has_additional_A             additional_AAAA_count    0.016324
                 ablate_top__has_additional_A                  dns_count_add_rr    0.013801
                 ablate_top__has_additional_A               answer_record_count    0.012952
                 ablate_top__has_additional_A                answer_CNAME_count    0.011728
                 ablate_top__has_additional_A           additional_record_count    0.011401
                 ablate_top__has_additional_A                 dns_count_answers    0.010482
                 ablate_top__has_additional_A                 answer_AAAA_count    0.006390

## 8. 주요 그래프

아래 이미지는 파일로 저장된 PNG를 노트북 안에서 바로 보여줍니다.

### `metrics_comparison.png`

![](plots/metrics_comparison.png)

### `probability_distribution.png`

![](plots/probability_distribution.png)

### `confusion_matrix_all_current.png`

![](plots/confusion_matrix_all_current.png)

### `feature_importance_all_current.png`

![](plots/feature_importance_all_current.png)

### `confusion_matrix_dropped_shortcut_only.png`

![](plots/confusion_matrix_dropped_shortcut_only.png)

### `feature_importance_dropped_shortcut_only.png`

![](plots/feature_importance_dropped_shortcut_only.png)

### `confusion_matrix_shortcut_suspects_only.png`

![](plots/confusion_matrix_shortcut_suspects_only.png)

### `feature_importance_shortcut_suspects_only.png`

![](plots/feature_importance_shortcut_suspects_only.png)

## 9. 직접 필터링하기

아래 셀들은 사용자가 직접 feature set, comparison, feature 이름으로 필터링할 때 쓰는 셀입니다.

In [ ]:
feature_set = 'all_current'
metrics[metrics['feature_set'] == feature_set]

In [ ]:
feature = 'has_additional_A'
statistics[statistics['feature'].eq(feature)].sort_values(
    ['comparison', 'mann_whitney_u_pvalue', 'separation_score'],
    ascending=[True, True, False]
)

In [ ]:
feature_set = 'all_current'
importances[importances['feature_set'].eq(feature_set)].head(30)